### PR TITLE
Doc: updated installation of NodeJS, add paths for NMEA sample files + cosmetics 

### PR DESCRIPTION
**Pull request by MatsA**

### CODE REVIEW

**Comment by KEGustafsson** [comment]
Good to know that node script installation is now deprecated, this has impact to docker images too.

**Review by tkurki — CHANGES_REQUESTED** [review]
Why add the commands to find the paths of the sample files? Why would an end user need to find the paths? There are no instructions what the end user should do with the paths.

**Comment by MatsA** [comment]
Did a fresh install of the SK server and used the new documentation to check. 

What I missed at the end, after running the setup script and adding the admin account, was information about how to use the sample files. It's very nice to use the sample files to be acquainted with the functions of SK.

So below the heading "Set up data connections" I thought that the info for the paths was appropriate. The paths to the files have changed during different versions of the SK server so instead of a fixed path to the file I used the command to find the file.

**Comment by MatsA** [comment]
Absolutely it's documented how to use it from command line. The first 2 ways will threw some confusing errors IF you have run the **setup script** since one instance of the SK server is already running...

The 3:d way is as said command line. 

The above could be a  little confusing for a newbie which I think is addressed in these pages of documentation.

When I'm testing things, NodeRed, new plugins and so on, I'm using sample files on a test server at home. Most often I'm using own recorded files but sometimes the mentioned sample files delivered with SK.

I thought this use case could be appropriate for other users starting up/using SK. It was also mentioned in the old documentation.

But as usual, no big deal just trying to help.

**Comment by tkurki** [comment]
I really appreciate your contributions! Don’t get me weong.

I just don’t see how an end user would benefit from knowing the path to the sample files, with no additional instructions what to do with the path.

**Comment by MatsA** [comment]
Ok, you got a point ..... Will do an update later on.

**Comment by tkurki** [comment]
I'd like to get this updated & merged, please.

**Comment by MatsA** [comment]
My sincere apologies for the delay !

**Comment by tkurki** [comment]
Thanks! Now the docs document the use of FileStream connection type, that people regularly ask about.

**Pull request merged**
