### PR TITLE
Appstore UI/column version

### PR DESCRIPTION
**Pull request by leonardgable**
Created a dedicated column version on the appstore page. This aims at resolving the confusion from user while browsing for plugins. 

Few users complained about the version number being detrimental to plugin search.

Also improved the responsivity of the search bar on mobile version. 

NOTE: I also removed the last updated date as it is not working well with the new column. Maybe we should display that information with a tooltip or differently.

### CODE REVIEW

**Comment by tkurki** [comment]
I don't want to lose the updated information. Now that the new appstore has had it it has proven valuable: All sorted by updated brings up the plugins that have updates or are new and seeing when it was updated gives nice context to the plugin.

**Comment by leonardgable** [comment]
> I don't want to lose the updated information. Now that the new appstore has had it it has proven valuable: All sorted by updated brings up the plugins that have updates or are new and seeing when it was updated gives nice context to the plugin.

Hi teppo, 

Thank you for your feedback. I have added the last update on the action column as it is closely related to the action of "updating" and "installing". I think it makes more sense to display it in this column.

Besides this column is always displayed even on the smallest screen, I think it will be good as it remains visible to the user on any screen size.

**Comment by tkurki** [comment]
Placing it in the action column takes up a a lot of vertical space, causing large empty areas and making the list needlessly tall. The Plugin and App badges also look now weird, as they are aligned to the middle of the whole row, not ligning up with anything else like they do currently with the Install button.

image
image

I think we should
- keep the top aligned columns together => so Type and Action are the last columns
- put Version and Updated in the same column, Updated underneath, without any label - I think it is obvious from the context that it is when the version was published
- put Version as the second column: Name and Version are the most important columns, so start with them

**Comment by leonardgable** [comment]
> Placing it in the action column takes up a a lot of vertical space, causing large empty areas and making the list needlessly tall. The Plugin and App badges also look now weird, as they are aligned to the middle of the whole row, not ligning up with anything else like they do currently with the Install button.
> 
> image image
> 
> I think we should
> 
> * keep the top aligned columns together => so Type and Action are the last columns
Done
> * put Version and Updated in the same column, Updated underneath, without any label - I think it is obvious from the context that it is when the version was published
Done
> * put Version as the second column: Name and Version are the most important columns, so start with them
Done


let me know what you think like this

**Comment by tkurki** [comment]
Your image does not show for me.

**Comment by tkurki** [comment]
Tried it - nice!

**Pull request merged**
