### PR TITLE
chore: upgrade to canboatjs 2.x and n2k-signalk 3.x

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by tkurki** [comment]
I'd like to have a Docker image built for this so that testing in real world would be easier, but build fails with `No matching version found for @signalk/n2k-signalk@^3.0.0.`. Maybe publish betas of the dependencies, so that we can move towards a beta release and people testing this?

**Comment by sbender9** [comment]
I published n2k-signalk 3.0.0-beta.1 and updated the dependency

**Comment by tkurki** [comment]
Rebased on master & force pushed.

**Comment by tkurki** [comment]
Rebased & force-pushed

**Pull request merged**
