### PR TITLE
fix: communication.callsignVhf not set properly in baseDeltas.json

### PR DESCRIPTION
**Pull request by sbender9**
Fixes https://github.com/SignalK/n2k-signalk/issues/277

### CODE REVIEW

**Comment by rhbvkleef** [comment]
This PR is breaking. I already depend on the old (incorrect) behaviour. I know know about it, but maybe placing a warning in the release notes about this breaking change might be useful for others.

**Comment by KEGustafsson** [comment]
Noticed the same issues. Old value object structure was changed to nested value, which breaks plugins using old format.

@sbender9 @tkurki Would this PR be OK to fix the issue?
https://github.com/KEGustafsson/signalk-server/commit/c25d95dba42f018e10567c097addb3d61dfe540e

**Comment by sbender9** [comment]
You're essentially proposing to revert this PR?

**Comment by sbender9** [comment]
I think we need to get plugin authors to change, since this is not a value object in the spec.

**Comment by KEGustafsson** [comment]
Ok, then it is clear violation against to the specs.

This is kind of breaking change. Current format, as it is now, have been there quite long time. Is it easier to change specs than plugins, databases, apps, etc...

**Comment by panaaj** [comment]
Also an observation, these deltas have a an empty path rather than "communication"


________________________________

**Comment by sbender9** [comment]
@tkurki what do you think? 

This is a tough one. In general, I would not want to make breaking changes to the spec either. I would also much rather this was not a value object.

**Comment by KEGustafsson** [comment]
I think this has been reference for callSign rather than specs. No path, but only value object.
https://github.com/SignalK/nmea0183-signalk/blob/master/hooks/VDM.js#L227-L232

**Comment by sbender9** [comment]
And of course, n2k-signalk does it per the spec. https://github.com/SignalK/n2k-signalk/blob/3b0401af0738c3fd8097ac661e060cdf4b9296cc/pgns/129794.js#L53

**Comment by sbender9** [comment]
Given that any plugins, etc. that use it are already broken for n2k sources, I think we should stick with the current spec and fix 0183.

**Comment by KEGustafsson** [comment]
Thats clear then. Nmea0183 and the rest using value object need to updated.
What is target for next SK release? I think common target should be simultaneous updates for server, plugins & apps. Otherwise it will be a mess.

**Comment by sbender9** [comment]
Yes, that's the correct format.  

Unless @tkurki has a date in mind, we don't have any target. 

We can definitely coordinate the releases.

**Pull request merged**
