### PR TITLE
feature: make Seatalk 1 python3 compatible (pigpio-seatalk.js)

### PR DESCRIPTION
**Pull request by sailoog**
Seatalk streams are broken in python3. filter function no longer returns a string, it return a filter object that must be joined.

### CODE REVIEW

**Comment by tkurki** [comment]
Is this backwards compatible?

**Comment by sailoog** [comment]
Sorry for the delay. Probably not, let me make some changes to make it compatible with python2 and python3.

**Comment by tkurki** [comment]
Any news on this?

**Comment by sailoog** [comment]
sorry, coming back from vacation. I will pull something ASAP

**Comment by sailoog** [comment]
Done, this will work for Python2 and 3, sorry for the delay again

**Comment by sailoog** [comment]
Why is it not passing the CI test? trying to interpret python code as js?

**Comment by tkurki** [comment]
run `npm run format` in packages/streams - there just an extra empty line that the formatter (prettier) doesn't like.

**Comment by sailoog** [comment]
Offending line removed and verification passed

**Comment by tkurki** [comment]
Thanks!

**Comment by tkurki** [comment]
This should be available in v1.46.3 shortly https://github.com/SignalK/signalk-server/releases/tag/v1.46.3

**Comment by sailoog** [comment]
thanks a lot, I will update openplotter ASAP

**Comment by sailoog** [comment]
something happens, I have updated to 1.46.3 but the old pigpio-seatalk.js is still there

**Comment by tkurki** [comment]
I forgot to create a new version of streams. Will fix…

**Comment by tkurki** [comment]
https://www.npmjs.com/package/@signalk/streams 2.2.1 has this change and a server update/install should now pull this, latest 2.x version.

**Comment by sailoog** [comment]
it works now, thanks!

**Pull request merged**
