### PR TITLE
fix: enable meta deltas from n2k-signalk

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Review by tkurki — COMMENTED** [review]
Should nmea0183_signalk calls in simple be updated also?

**Comment by sbender9** [comment]
> Should nmea0183_signalk calls in simple be updated also?

Why?

**Comment by tkurki** [comment]
Sorry, I was barking up the wrong tree.

But isn't passing `sendMetaDeltas` from simple to `streams/n2k-signalk` a k a `N2kToSignalK` dead code, as `streams/n2k-signalk` is hardcoded to pass true tp `@signalk/n2k-signalk` ?

**Comment by sbender9** [comment]
yeah...what was I thinking?

**Pull request merged**
