### PR TITLE
chore: upgrade admin ui to webpack 5

### PR DESCRIPTION
**Pull request by tkurki**
I built admin ui's package.json and webpack config from
scratch, mostly with the same major versions as previously.

.babelrc is apparently no longer needed.

The weird directory index package.jsons were no longer
working, so they are removed.

### CODE REVIEW

**Comment by sbender9** [comment]
Can you fix the conflicts?

**Comment by tkurki** [comment]
Fixed.

**Comment by KEGustafsson** [comment]
Tested this out of curiosity, but build failed to `"build": "webpack -p"`.
Changed from `"build": "webpack -p"` to `"build": "webpack --progress"` in the [package.json](https://github.com/SignalK/signalk-server/blob/webpack-5/packages/server-admin-ui/package.json#L49) and then build was OK.

**Comment by tkurki** [comment]
Did you clear & reinstall all depencies under the admin ui?

**Comment by tkurki** [comment]
Thanks, it is broken,  fix to follow..

**Comment by KEGustafsson** [comment]
Now it is working. I'll continue to use this one and if I find any issues I'll report here.

**Pull request merged**
