### PR TITLE
fix: don't send meta data over ws by default

### PR DESCRIPTION
**Pull request by sbender9**
If you want to get meta deltas add `?sendMeta=all` to your ws url.

### CODE REVIEW

**Comment by tkurki** [comment]
This will grow the size of the initial burst of data quite a lot. Do we really want to do this by default?

Meta is available via http on demand, like it has been, so things work the same as so far even with the addition of meta deltas.

**Comment by sbender9** [comment]
Makes things more complicated for the client if we don't do this. Now a client that doesn't need to make any REST calls has to have some special logic to get meta via REST if it doesn't come over WS. Why even send meta deltas then? A client that needs meta for everyting is going to have to make REST calls for everything in that initial burst.

**Comment by sbender9** [comment]
Also, although it does increase the initial burst, it does increase the total amount of data sent. Since they would be sent later anyway.

**Comment by tkurki** [comment]
Yes, I am talking about the whole mechanism of sending meta by default, not this specific pull request.

We have had meta for ages and it has not been sent by default. Clients that have needed it have been able to retrieve it via http. I agree that this adds a bit of complexity, but  judging from the lack of discussion in this area I don't think that this has been a big issue. 

Afai understand the main driver the meta deltas is the ability to add meta to the system, and sending all meta over ws is now an option that we have.

Now that we have the mechanism for sending metadata it makes perfect sense to have the **option** of getting metadata for all paths, but I think we should keep the default as it is and make metadata over ws optionally available.

The data volume increase is probably negligible, but if a client does not need metadata it won't be retrieved or sent anyway. Or what am I missing something something re: _sent anyway_? If something in the system puts out periodically meta deltas I am ok with passing them even if the client has not requested metadata.

**Comment by sbender9** [comment]
I'm ok with a query parameter. `sendAllMetaData`?

**Comment by tkurki** [comment]
Can you think of other then boolean values for this? `subscribe` is concise and allows extention via new values, but `sendCachedValues` is in retrospect a little unwieldy and an enum with values like `all` and `none` is more future proof.

Can there be multiple values to this?

**Comment by sbender9** [comment]
We already have `sendMeta` query parameter. Should we just change the default to `none` ?

https://github.com/SignalK/signalk-server/blob/master/src/interfaces/ws.js#L172

**Review by tkurki — APPROVED** [review]

**Pull request merged**
