### PR TITLE
Feature: indicate clearly that a plugin needs configuration

### LINKED ISSUE #1601: When plugin is not enabled, this should be visible clearly
Right now, especially for newbie or occassional user (me) the way signalk handles installing plugins adds a lot to the complexity of getting things going.

First picture below shows how it looks after installing a plugin, note how its not visible anywhere that the plugin (freshly installed) is disabled.

There already is a UX method for showing a non-enabled plugin, see bottom picture. 

My recommendations:

1. always show that enable/disable slider, also for freshly installed plugins, even if they need configuration first.
2. make the slider more visible when disabled, like red background.
3. clearly show "restart pending"

Picture 1: freshly installed plugin:

IMG_9936

Picture 2: other options:

image

### PR DESCRIPTION
**Pull request by JacoKoster**
Fixes #1601 

image
image

### CODE REVIEW

**Comment by tkurki** [comment]
The admin UI is far from pixel perfect, but I think vertical alignment could use a bit more love:

image

**Comment by JacoKoster** [comment]
@tkurki You are definitely right. Fixed now :) 
image

**Comment by tkurki** [comment]
Better, but it looks like the text baseline is now off

image
image

**Comment by JacoKoster** [comment]
image

Fixed :-)

**Comment by tkurki** [comment]
👍 just run `npm run format` in `packages/server-admin-ui` and we're done here.

**Comment by JacoKoster** [comment]
I also resolved the merge conflict with the Data Logging label :)

**Pull request merged**
