### PR TITLE
fix: connect to Signal K stream with self-signed certificate

### PR DESCRIPTION
**Pull request by cmotelet**
Allow connect to Signal K provider with self signed certificate #965
image

### CODE REVIEW

**Comment by tkurki** [comment]
package.json should probably say `@signalk/client: "^2.1.1"`?

**Comment by tkurki** [comment]
Having slept on this I think we are going in the wrong direction, adding more specific WebSocket connections, instead of having just one WebSocket source and adding `[ ] use SSL` and `[ ] allow self signed SSL Certificates`.

The problem comes with discovery: in principle you would pick WebSocket and say `use discovery` and things should work, without specifying ws versus wss and there `allow self signed certs` should be also an option.

@sbender9 @cmotelet your thoughts?

**Comment by cmotelet** [comment]
You're thinking of one swith button [allow self signed...]
The connection process will try automaticaly:
check [wss] then if KO check [wss self signed if allow] then if KO check [ws] and if KO report error in GUI
Yes, it's easier for the user.
Strong error management will be required during the checks to provide a clear message to the user.
Or just 'cannot connect see Server log...'

**Comment by tkurki** [comment]
I was thinking of a ui where you have only WebSocket in the popup menu and then 
- host
- port
- [ ] useSsl
- [ ] allow self signed certificates (greyed out if useSsl is false)

**Comment by sbender9** [comment]
How's it going with this?

**Comment by cmotelet** [comment]
Closed for rebuild from scratch

**Pull request closed without merging**
