### PR TITLE
fix: resource-provider server-api dependency

### PR DESCRIPTION
**Pull request by panaaj**
Add `@signalk/server-api` as a dependency rather than a dev-dependency.

This fix is included as part of v1.2.1 release.

### CODE REVIEW

**Comment by tkurki** [comment]
I thougth server api was just typescript and not used in runtime at all. Why is it needed?

**Comment by panaaj** [comment]
> I thougth server api was just typescript and not used in runtime at all. Why is it needed?

As a dev-dependency the plugin failed to load when the server starts citing unable to find sever-api references.
The Freeboard-SK plugin also needs it as a dependency also, there clearly a runtime requirement created by tsc.

**Comment by tkurki** [comment]
I see some consts and a class now, not just types and interfaces.

**Comment by tkurki** [comment]
Changed the label to chore so that this does not get grouped under fixes in release notes.

**Pull request merged**
