### PR TITLE
feature: support new meta deltas

### PR DESCRIPTION
**Pull request by sbender9**
TODO

- [x] Update UI code to edit the default deltas

### CODE REVIEW

**Comment by sbender9** [comment]
Wasn't not sure how to implement this in streambundle, very hacky right now.

**Comment by sbender9** [comment]
@tkurki I think this stuff is ready, but I can't figure out why some tests are failing.

**Comment by sbender9** [comment]
Not ready. Broke a bunch more tests with  my latest change...

**Comment by tkurki** [comment]
Closing as stale, reopen when needed.

**Pull request merged**
