### PR TITLE
Add support for Seatalk1 on Raspberry Pi 5

### PR DESCRIPTION
**Pull request by astuder**
As discussed in issue #1658 the existing integration of Seatalk1 does not work for Raspberry Pi 5 as the underlying Python library doesn't support the Raspberry Pi 5.

This pull-request uses the gpiod Python library to implement the functionality. This library is also supported by older versions of Raspberry Pi OS and hardware, so it could eventually replace pigpio.

I added a new field GPIO Library to the connection dialog to select between gpiod and pigpio. 

I tested this pull request on a Raspberry Pi 5.

The standalone Python script (available [here](https://gist.github.com/astuder/c319cf955f6d651350222d36065981b3)) was successfully tested on Raspberry Pi 3, 4 and 5, running Raspberry Pi OS Bookworm and Bullseye.

### CODE REVIEW

**Review by tkurki — COMMENTED** [review]
I think the approach is sound and not being a Pythonist nor a Seatalk user I don't have much to comment on here. 

Let's try to get the doc update in https://github.com/SignalK/signalk-server/pull/1780/commits/46649387e6ebe3d64e076680611ea3c1795bcb66 included in this PR, makes for a little nicer Release Notes.

**Comment by astuder** [comment]
merged documentation updates provided by @sailoog

**Comment by tkurki** [comment]
Please `npm run format` the ui code, see the failed test.

**Comment by astuder** [comment]
done

**Pull request merged**
