### PR TITLE
feature: add write statistics to dashboard

### PR DESCRIPTION
**Pull request by tkurki**
Add new icon to indicate outbound traffic on Connections.

Change the previous feed icon to 'login' to indicate incoming traffic so that we can use the 'logout' icon for outbound traffic.

image

### CODE REVIEW

**Comment by cmotelet** [comment]
- reading file: /lib/node_modules/signalk-server/samples/aava-n2k.data
- activity on file as input with icon blinking : OK
- SignalktoN2K with COG&SOG enable: OK
- candump on vcan0, I read PGN129026 with COG&SOG values on the bus: OK
- But no out activity icon on vcan0: KO
It's seem the same with NMEA0183.
image

What is your test protocol to icon out visible and blinking ?

**Comment by tkurki** [comment]
See the files that I touched: connections using serial, tcp (client) and simple. How did you set up vcan0?

@sbender9 am I missing something here?

**Comment by cmotelet** [comment]
```
      "pipeElements": [
        {
          "type": "providers/simple",
          "options": {
            "logging": false,
            "type": "NMEA2000",
            "subOptions": {
              "type": "canbus-canboatjs",
              "interface": "vcan0",
              "useCanName": true,
              "uniqueNumber": 1445085
            }
          }
        }
      ],
      "id": "vcan0",
      "enabled": true
```
vcan0 configured through GUI 
my vcan0 works in input mode, I can read data in SignalK sent by another process

**Comment by cmotelet** [comment]
I just remembered that on configuration I am always with nodejs16. I didn't get any alerts during npm install nor when building the server, only when launching.
And if I'm the only one having a problem, it's probably mine.

**Pull request merged**
