### PR TITLE
feature: use Node 16, remove HTTP/2 support

### PR DESCRIPTION
**Pull request by tkurki**
- run tests with 16 (and legacy 10)
- specify >10 in package.json
- specify 16 in nvmrc

See also #1133

### CODE REVIEW

**Comment by tkurki** [comment]
Thanks for testing. Errors related to Node version are
- Unsupported engine => fixed by this PR, once merged and published
- DeprecationWarning => I'll see about this

The others are unrelated to Node version upgrade.

**Comment by tkurki** [comment]
Trace
```
(node:34893) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
    at process.binding (node:internal/bootstrap/loaders:133:17)
    at Object.<anonymous> (/Users/teppokurki/git-workspace/signalk/server/node_modules/http-deceiver/lib/deceiver.js:22:24)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/teppokurki/git-workspace/signalk/server/node_modules/spdy/lib/spdy/handle.js:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
```

**Comment by tkurki** [comment]
spdy that is used for HTTP/2 support appears to have problems with Node >= 15 https://github.com/spdy-http2/node-spdy/issues/380

I don't think HTTP/2 support is needed in SK server, so I'll see about removing it or making it an optional dependency.

**Comment by tkurki** [comment]
If you want to try the version in this branch pull it from Github and
- npm install && npm run build
- bin/nmea-from-file

**Comment by KEGustafsson** [comment]
Been also running Node16 for sometime in one dev machine and no issues with SK server.

Server-admin-ui and server-admin-ui-dependencies seems to require some dependency updates due to Node16 to get my own ui modifications running with new node version.

**Comment by MatsA** [comment]
Tried to test ...

pi@raspberrypi:~/signalk-server-node $ npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

pi@raspberrypi:~/signalk-server-node $ npm run build
> signalk-server@1.40.0 build
> tsc

pi@raspberrypi:~/signalk-server-node $ bin/nmea-from-file
/usr/bin/env: ‘node --trace-deprecation’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines

a little over my knowledge....    ;-)

**Comment by tkurki** [comment]
@MatsA thanks, I had accidentally committed --trace-deprecation, fixed now in Github version.

**Comment by MatsA** [comment]
OK, new version tested and works very well, no errors in the server log. The warnings are almost the same in the installation

npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

Tested with, Freeboard, charts plugin, and AIS input as UDP data. If you think its needed I can test serial, Acticense, input in the boat ? 

Any other thoughts ? 

/Mats

**Comment by tkurki** [comment]
@KEGustafsson please share what changes you needed to do in those packages.

**Comment by tkurki** [comment]
@MatsA since serial connections need native binary modules those are more risky in terms of compatibility, so that's what I'd test next.

**Comment by KEGustafsson** [comment]
> 
> 
> @KEGustafsson please share what changes you needed to do in those packages.

@tkurki These were the modification that I made.

`server-admin-ui-dependencies`
[server-admin-ui-dependencies.patch.txt](https://github.com/SignalK/signalk-server/files/7490930/server-admin-ui-dependencies.patch.txt)
and then `npm pack` and used that locally in server-admin-ui as a dependency.

`server-admin-ui`
[server-admin-ui.patch.txt](https://github.com/SignalK/signalk-server/files/7490929/server-admin-ui.patch.txt)

**Comment by MatsA** [comment]
@tkurki OK, tested with Actisense NGT-1 and no problem.

But missed a problem with NodeRed, from server log
(node:5825) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/pi/signalk-server-node/node_modules/@node-red/editor-client/package.json' of './lib/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
signalk-server running at 0.0.0.0:3000

Did an upgrade 
pi@raspberrypi:~/signalk-server-node/node_modules/@signalk/signalk-node-red $ npm install node-red@latest
and it solved the problem !

Additional apps tested

@signalk/charts-plugin
@signalk/signalk-node-red
@signalk/vedirect-serial-usb
signalk-ruuvitag-plugin
signalk-shelly

and some UDP sources and no problem.

Think that the Avahi warnings could be a bit annoying for newbies ? The project https://github.com/homebridge/homebridge had the same problem for a year ago. Maybe could get a hint from their code ?

**Comment by tkurki** [comment]
Agreed, Avahi warnings are a nuisance. Looked into Homebridge and added #1353 to cover that issue.

**Comment by tkurki** [comment]
@KEGustafsson thanks. Do you remember what kind of trouble you had with Redux? Just wondering if the issue may have been resolved in an updated Redux and no longer needs action.

**Comment by KEGustafsson** [comment]
> 
> 
> @KEGustafsson thanks. Do you remember what kind of trouble you had with Redux? Just wondering if the issue may have been resolved in an updated Redux and no longer needs action.

No specifix problem with Redux but `npm install` caused errors during build and these modifications removed issues.

**Comment by tkurki** [comment]
Related OpenPlotter discussion https://forum.openmarine.net/showthread.php?tid=3765&pid=21062#pid21062

**Comment by MatsA** [comment]
OK. Since the boat is on the hard, the engines are winterized and I'm just waiting for to ski in the Alps during Christmas.... ;-)
... I did some more testing using Bullseye, with this branch and Node 16.

It works very well !!

pi@raspberrypi:~/signalk-server-node $ npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

Even the Avahi warnings disappeared ?? 

pi@raspberrypi:~/signalk-server-node $ bin/nmea-from-file
signalk-server running at 0.0.0.0:3000

Tomorrow, probably, I will check the serial interface in the boat with Actisense and some more plugins.
Is there anything else I can help with before this branch goes in production ?

**Comment by MatsA** [comment]
Don't know if it matters but installing the NodeRed plugin on Buster gave the path 
pi@raspberrypi:/home/pi/signalk-server-node/node_modules/@signalk/signalk-node-red
On Bullseye it gave
/home/pi/.signalk/node_modules/@signalk/signalk-node-red
?

**Comment by tkurki** [comment]
I think we should separate node 16 from Bullseye related details. If there's something odd going on please add an issue for it.

**Comment by MatsA** [comment]
Yes, one thing at a time. 
But maybe skip the planned Avahi update since it seems to be solved with Bullseye ? 
Thanks for the merge, will update the RPi installation with Node V16, when this PR is included in next release.

**Pull request merged**
