### PR TITLE
feat: ws connection name replaced with description on Dashboard Connections activity

### PR DESCRIPTION
**Pull request by KEGustafsson**
image

### CODE REVIEW

**Comment by tedenda** [comment]
Fixes #1146

Thanks!

**Comment by tkurki** [comment]
I think we should add this data to the connection information on the server, so that the ui would not need to fetch it separately. The security api also needs admin level access, if the server passes the data then that is not a problem for non admin users.

**Comment by KEGustafsson** [comment]
Non-admin use case was not considered, so this need redesign.

PR will be updated, when new approach is a bit more clear. This will need some investigations.

**Comment by KEGustafsson** [comment]
In addition to previous issue, there is noticeable performance degradation in slow networks, which makes this approach not usable. One more thing, which drives this PR back to drawing board.

**Pull request closed without merging**
