### PR TITLE
feature: support openApi in plugins

### PR DESCRIPTION
**Pull request by tkurki**
Allow plugins to expose OpenApi descriptions by implementing getOpenApi method. The description will be included in the server's OpenApi UI apis list.

- [x] update SERVERPLUGINS.md

### CODE REVIEW

**Comment by tkurki** [comment]
@meri-imperiumi see `test/plugin-test-config/node_modules/testplugin/index.js` for an example, you can npm link that directory to the server to check this out quickly.

**Comment by bergie** [comment]
It would be nice to produce one merged OpenAPI document for the server including APIs provided by all installed plugins. But this is certainly a good start!

**Comment by tkurki** [comment]
Can u explain a little more in what case it would be better? A single document and the resulting Swagger api seems pretty unwieldy to me. See also #1502.

Would a search over the different apis solve your use case?

**Comment by bergie** [comment]
In my view it shouldn't matter which _source_ provides an API, but instead what the API does. But maybe that would indeed become unwieldy in a "free-for-all" environment like the SK plugin space. Hard to enforce consistency...

**Comment by tkurki** [comment]
Ah, my point was not that it matters which source provides an API. I think the way forward here is to have 
- offical SK APIs
- plugin-specific APIs
and things can evolve so that an API starts as a plugin-specific api and then is adopted/promoted to "official" SK api.

Which means that we do need a way for manage this change.

But I think I'll merge this PR shortly to include it in the next beta.

**Pull request merged**
