### PR TITLE
feature: connection activity indicator updates

### PR DESCRIPTION
**Pull request by KEGustafsson**
Update to Connection activity view of Signal K server admin UI.

Ingress and Egress icons:
- light blue until traffic is detected
- pulsed dark powder blue (`#039`) when traffic is detected
- solid dark powder blue after data connection opened but no traffic is detected

Values shown only when traffic detected:
- deltas/s (ingress)
- msg/s (egress)

### CODE REVIEW

**Comment by tkurki** [comment]
So now it looks like this (without the pulse effect):

conn_activity

- rate unit labels: either have them inline or at the title, not both. if inline I think the unit should come after the number
- my head hurts with delta/s, should be deltas/s, like in total server throughput

A thought for the future, not for this PR: By adding the output indicator it kinda looks like output is relevant for all connections and plugins, which is not the case. And vice versa, input may not be relevant for some of these (derived data for example). So fundamentally there is a difference between "never having input/output something" (blue) and "input/output not being relevant at all" (now indistuingisable from blue). Should we have a way for connections and plugins to say which are relevant and have it visualised somehow?

**Comment by KEGustafsson** [comment]
delta/s -> deltas/s, this typo and will be corrected.

deltas/s, msg/s units and location is something which need some trials to figure out which layout is looking best. Without units, it could be a bit challinging to say is it ingress or egress if traffic is uneven and you have to see type from icon first. I will do improvements here and prose a new set.

About plugin or connection data flow directions. It would be nice to have ingress, egress and ingress&egress grouped, now mixed rendered from same order as they appear in the array.

Later, it could be practical if plugins and connections would indicate if they are in, out or in/out relays.

**Comment by mpvader** [comment]
Hi, nice improvement. I've seen that for the first time today, at first while there was no data going in and out Signal K server; how about showing 0 delta/s when there are no deltas?

Advantage is that a user of non-working system can see better what to expect when it does work. Now he'd see this:

image


And secondly, a mouse over over those icons would be nice, at a minimum saying what they are: `data ingress indicator` / `data egress indicator`.

And maybe current status with regards to what the current icon means?

ps. mainly for myself, picture of how it looks normally:

image

**Comment by KEGustafsson** [comment]
There will be improvements to show more egress data information. Then more UI improvements could be included.

0 deltas/s or 0 msg/s were on purpose left blank to improve indication of active connections. Does 0 improve information to end users. Might be or not.

Also grouping to connections and plugings is under planning. That would improve readability too.

There are no hoverings at the moment, but might be nice thing to add.

**Pull request merged**
