### PR TITLE
[WIP] function to update plugin configuration before starting it

### PR DESCRIPTION
**Pull request by cmotelet**
Recently, I wanted to update the GUI schema and configuration of the `signalk-to-nmea0183` plugin.
I realized that the access to the configuration of a plugin is only accessible inside the `start` function.
And so it must be active to be able to update it.
If it is not active and the user tries to save the configuration, he receives an error because the current configuration is too different from the new schema.
The purpose of this PR is to call a function `plugin.updateConfiguration` if it exists in the plugin when the plugin is discovered.
The plugin can update its configuration and add a version number.
If the version number is different, `signalk-server-node` automatically saves the new version before launching the plugin.
I don't know if it's better to use a specific version number for configuration or to reuse the version number of the plugin ?

Before updating `SERVERPLUGINS.md` to describe this function, I would like to know if this seems sufficient.
I'm not sure this option will be used much so it may not be necessary to make it more complex.

And an additional question about naming:
`options` or `configuration` ?
Since there are already savePluginOptions and readPluginOptions, it may be embarrassing to talk about configuration.

Comments are welcome.

### CODE REVIEW

**Comment by tkurki** [comment]
I took a stab at making the server TypeScript, see #879. What if we finish that one first (assuming it does not stall)? and then redo this, in ts?

**Comment by cmotelet** [comment]
Work on this PR is suspended and will be resumed after migration to TypeScript

**Comment by tkurki** [comment]
Now that #879 is merged & published let's continue!

**Comment by tkurki** [comment]
I got started with a bit different approach, but it is too raw to share at this point.

**Comment by cmotelet** [comment]
too old and outdated

**Pull request closed without merging**
