### PR TITLE
Fix: Issue when creating resources via plugin interface

### LINKED ISSUE #1600: Resource provider error with more than one custom resource type
My resource provider configuration (see below) includes two custom resource
types. Directories for both resource types are created normally.

I can access the first custom resource type ('metadata') without any problems, but
attempts to access the second custom resource type ('metadata-snapshot') fail
with the error 'No provider for metadata-snapshot'.

The call triggering the error expands to
```
app.resourcesApi.setResource('metadata-snapshot', 'test', '{ "value": "foo"}');
```

Resource provider configuration:
```
{
  "configuration": {
    "standard": {
      "routes": true,
      "waypoints": true,
      "notes": true,
      "regions": true
    },
    "custom": [
      {
        "name": "metadata"
      },
      {
        "name": "metadata-snapshot"
      }
    ],
    "path": "./resources"
  },
  "enabled": true,
  "enableLogging": false,
  "enableDebug": true
}
```

### PR DESCRIPTION
**Pull request by panaaj**
Added additional checks for identifying provider when using `setResource()`.
Fixes issue where creating a new resource entry was failing.

Fixes #1600

### CODE REVIEW

**Comment by tkurki** [comment]
@preeve9534 any feedback on this?

**Comment by preeve9534** [comment]
Just returning to harbour. Will take a look promptly.

**Comment by preeve9534** [comment]
See #1600

**Comment by preeve9534** [comment]
When I got my head sorted...
This seems to have fixed #1600.

**Pull request merged**
