### PR TITLE
doc: add Authentication and Session Management

### PR DESCRIPTION
**Pull request by tkurki**
Add documentation & guidance to clear up confusion about how the authentication and session management work.

### CODE REVIEW

**Review by panaaj — COMMENTED** [review]
Are there use cases where token authentication is appropriate?
Eg using app as non admin user on the same device where admin UI is logged in with admin user.

It may be worth mentioning.

**Comment by tkurki** [comment]
@panaaj can you elaborate? Don’t quite understand the use case.

Also let’s be precise: ”device” is pretty ambiguous. I assume you mean ”on the same browser”?

**Comment by panaaj** [comment]
My point is, the document mentions token authentication (although discouraging it) which is fine, but the fact that it can be used at all warrants some guidance of how to use it appropriately.

**Use case:**
1. Webapp, that stores user preferences on the server in `applicationData`, is in use and logged in with a "non-admin" user.
2. User then opens a new tab in the same browser and loads the Admin UI to make some configuration change that requires login as an "admin user".

**Requirement:** 
- Logging in to the Admin UI should not impact the WebApp operation by changing the authenticated user.

If the WebApp is using token authentication then it will not be impacted by the user logged in to the Admin UI.

**Comment by tkurki** [comment]
I think _token in header_ based authentication was originally created for authenticating devices and applications that are not browsed based and don't have cookie management. To be honest I did not understand that there were webapps using it - I thought that "everybody" was using cookies. I included it for completeness, not for use in particular scenarios in webapps.

As I see it the problem with mixing cookie and token based authentications is that token based app's login changes session based app's session, but not the other way around. @panaaj the scenario you outlined is really strict: it works only when token based app has logged in first.

If there is real need for having separate sessions for different webapps then we can build in explicit support for it, so that there is no confusion. With the current landscape of webapps and closer integration between Freeboard and Kip I don't quite see the value for the user. 

I force pushed small tweaks. If you feel there's room for improvement feel free to make it better, I am ready to merge.

**Comment by panaaj** [comment]
I think it's ok for now. It outlines the operation and the requirements for token use for apps. 
It's better to have some guidance than none at all, even if there is potentially some more work to do.

**Pull request merged**
