### PR TITLE
SK Server Admin UI Activity View Update

### PR DESCRIPTION
**Pull request by KEGustafsson**
This PR introduces changes to `Connection activity` view on SK Admin UI.
Currently activity view is mixed list of `Connections` and `Plugins` activities and list is not sorted at all.
Update will split activities to `Connections` and `Plugins` and sort list in alphabetic order.

Example view:
image

### CODE REVIEW

**Comment by tkurki** [comment]
The headings could be "heavier", so that you can tell that they are headings for the list below.

Don't know how relevant in real life, but if there's no plugin activity the heading looks a little oprhaned

image

**Comment by tkurki** [comment]
Minor nuisance, but now all Connections link to Connections page, even if just some of them can be configured there.

**Comment by KEGustafsson** [comment]
Pretty much all fixed now from activity view.

**Comment by tedenda** [comment]
Could #1146 also be looked at in this PR?

**Comment by tkurki** [comment]
Related but independent, better kep separate. But I hear you…

**Comment by KEGustafsson** [comment]
Duplicated/similar code parts are removed.

**Comment by KEGustafsson** [comment]
Fixes and optimizations for Dashboard starts to be finalized for now.

If still something need to be changed or added ok, otherwise ready for review.

**Pull request merged**
