### PR TITLE
feature: add 'AccessLogging' as an option to the Server Settings

### PR DESCRIPTION
**Pull request by jakobdalsgaard**
Adding 'AccessLogging' as an option to the server in order to control whether the Morgan web server should produce access log output.

### CODE REVIEW

**Comment by tkurki** [comment]
Looking forward to merging this! Could you please rebase this on master and do `npm run lint`, formatting needs a little improvement.

**Comment by tkurki** [comment]
With no `accessLogging`configured in settings.json this will show accessLogging being on in the UI but in truth it will be off.   I think we can change access logging to be off by default (= not specified in settings), but the UI needs to reflect that correctly.

**Comment by jakobdalsgaard** [comment]
If your settings.json does not deliver an accessLogging boolean, then the UI reflects what's in serverroutes.js, right?

I guess setting a default value would be done in 'readSettingsFile' in config.ts -- is that correct?

I furthermore guess that if accessLogging is set there, then UI and behaviour will be aligned, regardless of what we set it to.

I can try and set it to false and see.

**Comment by jakobdalsgaard** [comment]
If your settings.json does not deliver an accessLogging boolean, then the UI reflects what's in serverroutes.js, right?

I guess setting a default value would be done in 'readSettingsFile' in config.ts -- is that correct?

I furthermore guess that if accessLogging is set there, then UI and behaviour will be aligned, regardless of what we set it to.

I can try and set it to false and see.

**Comment by tkurki** [comment]
I was thinking that the code should behave correctly even in the absence of `accessLogging` in the setting file.

**Comment by tkurki** [comment]
Thanks for the nudge, now in master via #1471.

**Pull request closed without merging**
